import setuptools

setuptools.setup(
    name="lokki", 
    version="0.0.1",
    author="Michael Greer",
    author_email="michael.j.greer1@gmail.com",
    description="Lokki: a machine learning library for performing integrative analysis across various machine learning model and feature transformation combinations",
    long_description="Lokki: a machine learning library for performing integrative analysis across various machine learning model and feature transformation combinations",
    long_description_content_type="text/markdown",
    license='Apache 2.0',
    python_requires='>=3.6',
    install_requires=[
        'numpy==1.16.4',
        'pandas==0.25.0',
    ],
    url="https://github.com/pypa/sampleproject",
    packages=setuptools.find_packages(),
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        'Development Status :: 2 - Pre-Alpha',
        'Natural Language :: English',
        'Intended Audience :: Developers',
        'Intended Audience :: Education',
        'Intended Audience :: Science/Research',
        'Intended Audience :: Information Technology',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.6',
        'Topic :: Scientific/Engineering :: Information Analysis',
        'Topic :: Scientific/Engineering :: Artificial Intelligence',
        'Topic :: Scientific/Engineering :: Artificial Intelligence',
        'Topic :: Software Development :: Libraries',
        'Topic :: Software Development :: Libraries :: Python Modules',
    ],
    python_requires='>=3.6',
)
